name: HACS Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: "22.x"
          cache: npm

      - run: npm ci && npm run build

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: plugin
